<a href="https://colab.research.google.com/github/simonebugo/Big_Data/blob/main/6b_Preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Preprocessing data

### Standardization, or mean removal and variance scaling


Standardization of datasets is a common requirement for many machine learning estimators implemented in scikit-learn;

In practice we often ignore the shape of the distribution and just transform the data to center it by removing the mean value of each feature, then scale it by dividing non-constant features by their standard deviation.



in sklearn è possibile applicare delle tecniche per modificare i valori delle feature. abbiamo preso i valori delle 4 feature e abbiamo usato quei valori.  avremmo potuto applicare delle tecniche di scaling per modificare i valori e vedere se ha impatto sui risultati del ml. alcuni algoritmi funzionano meglio con valori scalati per es in un intervallo [0,1].
in sklearn ci sono diversi trasformatori che possono essere usati tutti allo stesso modo. hanno una funzione che si chiama fit che impara qualcosa dai dati e calcola delle funzione statistiche sui dati. es media deviazione standard ecc... e poi funzione trasform che permette di applicare trasformazione ai dati. poi c'è fit_trasform che fa entrambe le cose. prima fa la fit e poi trasforma i dati. vediamo alcune di qeuste possibil trasformazioni

In [1]:
#prima funzione: lo scaling.
from sklearn import preprocessing
import numpy as np
import pandas as pd

X_train = np.array([[ 1., -1.,  2.],
                    [ 2.,  0.,  0.],
                    [ 0.,  1., -1.]])

X_scaled = preprocessing.scale(X_train)   # default axis=0 standardize each feature

X_scaled

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

The standard score of a sample x is calculated as:
<tt>z = (x - u) / s</tt>
where u is the mean of the training samples or zero if <tt>with_mean=False</tt>, and s is the standard deviation of the training samples or one if <tt>with_std=False</tt>.


The preprocessing module further provides a utility class StandardScaler that implements the Transformer API to compute the mean and standard deviation on a training set so as to be able to later reapply the same transformation on the testing set.

standard scaler che applica una funzione ai dati per cui per ogni feature calcola media e deviazione standard. dopo ad ogni valore delle feature si sottrae
la media e si divide per la deviazione standard. i valori vengono trasformati in moco che ogni feature abbia media 0 e deviazione standard 1. alcun algoritmi fuznionano meglio con i valori a cui è applicato lo standard scaler.

In [2]:
sss = preprocessing.StandardScaler() #inizializzo standard scaler
scaler = sss.fit(X_train) #fit calcola medie e deviazione standard su traing
#una volta inizalizzato il trasformatore e applicata funzione di fit il trasformatore si può applicare su qualsiasi altro dato (anche sui dati di test)
#media e dev stanrd che userà sono quelle imparate dai dati di train

In [3]:
scaler.transform(X_train) #trasform va a modificare effettivamente i dati in x_train.

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

In [4]:
scaler.transform(X_train).mean(), scaler.transform(X_train).std() #controllo media e dev stanrd di ogni feature scopro che c'è una mediaa di 0 e una dev stardard di 1

(np.float64(4.9343245538895844e-17), np.float64(1.0))

The scaler instance can then be used on new data to transform it the same way it did on the training set



In [5]:
X_test = np.array([[ 2., -3.,  2.],
                    [ 2.,  5.,  0.],
                    [ 0.,  1., -1.]])

In [6]:
scaler.transform(X_test)

array([[ 1.22474487, -3.67423461,  1.33630621],
       [ 1.22474487,  6.12372436, -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

In [7]:
scaler.fit(X_train)
scaler.transform(X_train)

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

In [8]:
scaler.fit_transform(X_train)

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

### Scaling features to a range

An alternative standardization is scaling features to lie between a given minimum and maximum value, often between zero and one, or so that the maximum absolute value of each feature is scaled to unit size.

In [9]:
X_train = np.array([[ 1., -1.,  2.],
                    [ 2.,  0.,  0.],
                    [ 0.,  1., -1.]])

In [10]:
min_max_scaler = preprocessing.MinMaxScaler((0,1)) # default [0,1]
#min max scaler alrto tipo di trasformatore che applcia una trasforamzione per fare in mdoo che ogni feature abbai valori compresi tra 0 e 1. e ho feature con intervallo + alto questi valori
#vengono ritorri nell'intervallo [0,1] mantenendo i rapporti tra i vari valori. intervallo 0,1 è quello di default ma si può peronalizzare

In [11]:
min_max_scaler.fit(X_train)

MinMaxScaler()

In [12]:
min_max_scaler.transform(X_train)

array([[0.5       , 0.        , 1.        ],
       [1.        , 0.5       , 0.33333333],
       [0.        , 1.        , 0.        ]])

In [13]:
X_test = np.array([[-3., -1.,  4.]])
min_max_scaler.transform(X_test) #come visto prima una volta che ho creato il trasformatore, posso chiamare il trasformatore su un altro set di dati diverso da quello visto durante
#il fit del trasformatore


array([[-1.5       ,  0.        ,  1.66666667]])

The transformation is given by:

X_std = (X - X.min(axis=0)) / (X.max(axis=0) - X.min(axis=0))

X_scaled = X_std * (max - min) + min

If your data contains many outliers, scaling using the mean and variance of the data is likely to not work very well. In these cases, you can use robust_scale and RobustScaler (x_scaled = x / max(abs(x)))
as drop-in replacements instead. They use more robust estimates for the center and range of your data.



In [14]:
from sklearn.preprocessing import RobustScaler #anzi che usare media e deviazione standard, usa la mediana e l'interquartirle (differenza tra terzo quartile e primo quartile.)
X = [[ 1., -2.,  2.],
     [ -2.,  1.,  3.],
     [ 4.,  1., -2.]]

In [15]:
transformer = RobustScaler().fit(X)

In [16]:
transformer.scale_

array([3. , 1.5, 2.5])

In [17]:
transformer.transform(X)

array([[ 0. , -2. ,  0. ],
       [-1. ,  0. ,  0.4],
       [ 1. ,  0. , -1.6]])

la scleta del trasformatore usale non è banale, dobbiamo vedere la doc del algoritmo di ml che usiamo e capire se si è capito che c'è un trafsormatore cheva meglio. altrimento occorre fare dei test applicando diversi trasformatori.

The transformation is computed as:

<tt>X_scaled = (X - X.median(axis=0)) / X.IQR(axis=0)</tt>

where <tt>IQR = q3 - q1</tt>

The IQR is the range between the 1st quartile (q1) and the 3rd quartile (q3).

## Normalization


Normalization is the process of scaling individual samples to have unit norm. This process can be useful if you plan to use a quadratic form such as the dot-product or any other kernel to quantify the similarity of any pair of samples.

‘l1’
The l1 norm uses the sum of all the values and thus gives equal penalty to all parameters, enforcing sparsity.
x_normalized = x / sum(X)


‘l2’
The l2 norm uses the square root of the sum of all the squared values. This creates smoothness and rotational invariance. Some models, like PCA, assume rotational invariance, and so l2 will perform better.
x_normalized = x / sqrt(sum((i**2) for i in X))

normalizzazione fa in modo che la norma di ogni riga del dataset sia uguale a 1. la somma di tutti i quadrati se la calcoliamo è uguale a 1. altra tipoloia di trasformazione.

In [18]:
X = np.array([[1., -1.,  2.],
              [ 2.,  0.,  0.],
              [ 0.,  1., -1.]])
X_normalized = preprocessing.normalize(X, norm='l2')

In [19]:
# the same as previous X_normalized = preprocessing.Normalizer(norm='l2').fit_transform(X)

In [20]:
X_normalized

array([[ 0.40824829, -0.40824829,  0.81649658],
       [ 1.        ,  0.        ,  0.        ],
       [ 0.        ,  0.70710678, -0.70710678]])

In [21]:
np.sqrt(0.40824829**2 + 0.40824829**2 + 0.81649658**2)

np.float64(0.9999999988637723)

In [22]:
np.sqrt(0**2 + 0.70710678**2 + (-0.70710678)**2)

np.float64(0.9999999983219684)

You can refer to [https://scikit-learn.org/stable/auto_examples/preprocessing/plot_all_scaling.html](https://scikit-learn.org/stable/auto_examples/preprocessing/plot_all_scaling.html) for more details.

in questa pagine ci sono i diversi plot delle feature prima e dopo la trasformazione. vediamo come variano i valori prima e dopo la trasformazione

##  Encoding categorical features

### OneHotEncoder

abbamo ggià visto come modificare i valori categorici. si può fare la stessa cosa con il trasformer di sclearn. avevamo visto la funzione getdummies che permette di fare il one hot encoding. partendo da una feature  categorica posso ottenere tante feature numeriche con val 0,1 dove ogni colonne corrispnde un diverso valore della feature categorica.
si può fare con il onehotencore la stessa cosa

In [23]:
X = [['male', 'Spain', 'tennis'],
     ['female', 'Italy', 'football'],
     ['female', 'Italy', 'painting'],
     ['male', 'Spain', 'tennis'],
     ['female', 'France', 'football'],
     ['male', 'Italy', 'painting']]
X #3 colonne di dati differenti. la prima ha valori male female, la seconda spain,italyfrance, e la terza tennis footbal painting

[['male', 'Spain', 'tennis'],
 ['female', 'Italy', 'football'],
 ['female', 'Italy', 'painting'],
 ['male', 'Spain', 'tennis'],
 ['female', 'France', 'football'],
 ['male', 'Italy', 'painting']]

In [24]:
pd.DataFrame(X, columns=['gender', 'locations', 'hobby']) #partendo da feature creo dataframe per vedere meglio

gender locations     hobby
0    male     Spain    tennis
1  female     Italy  football
2  female     Italy  painting
3    male     Spain    tennis
4  female    France  football
5    male     Italy  painting

In [25]:
enc = preprocessing.OneHotEncoder() #applico onehotencoder in modo che non ci sia più colonna gender ma ce ne siano 2 chiamate male e female con i valori 0,1 idem per location e hobby
enc.fit(X) #fit su onehotencoder

OneHotEncoder()

In [26]:
enc.transform(X).toarray() #trasformo i dati di x (da valori categorici, ora ho valori 0 e 1)

array([[0., 1., 0., 0., 1., 0., 0., 1.],
       [1., 0., 0., 1., 0., 1., 0., 0.],
       [1., 0., 0., 1., 0., 0., 1., 0.],
       [0., 1., 0., 0., 1., 0., 0., 1.],
       [1., 0., 1., 0., 0., 1., 0., 0.],
       [0., 1., 0., 1., 0., 0., 1., 0.]])

In [27]:
enc.get_feature_names_out() #feature presenti nell'array nmpy trasformato ho trasforamto l'arraynumpy categorico in uno numerico

array(['x0_female', 'x0_male', 'x1_France', 'x1_Italy', 'x1_Spain',
       'x2_football', 'x2_painting', 'x2_tennis'], dtype=object)

In [28]:
enc.transform([['male', 'Italy', 'football'],
               ['female', 'France', 'painting']]).toarray()

array([[0., 1., 0., 1., 0., 1., 0., 0.],
       [1., 0., 1., 0., 0., 0., 1., 0.]])

In [29]:
enc.categories_

[array(['female', 'male'], dtype=object),
 array(['France', 'Italy', 'Spain'], dtype=object),
 array(['football', 'painting', 'tennis'], dtype=object)]

#### with fixed categories value

In [30]:
genders = ['female', 'male']
locations = ['Spain', 'France', 'Italy']
hobbies = ['football', 'painting', 'tennis']
enc = preprocessing.OneHotEncoder(categories=[genders, locations, hobbies])

X = [['male', 'Spain', 'tennis'],
     ['female', 'Italy', 'football'],
     ['female', 'Italy', 'painting'],
     ['male', 'Spain', 'tennis'],
     ['female', 'France', 'football'],
     ['male', 'Italy', 'painting']]

enc.fit(X)
#una voota che ho inizalizzato il onehoteencoder e l'ho trinato su alcuni dati lo posso applciare su dati diversi.

OneHotEncoder(categories=[['female', 'male'], ['Spain', 'France', 'Italy'],
                          ['football', 'painting', 'tennis']])

In [31]:
enc.transform([['female', 'USA', 'football']]).toarray() #lo appico per es ad una stringa feamel usa footbal. da però errore.
#errore indica che è stata trovata una categoria sconosciuta ovvero usa durante la trasfoarmazione (non c'era tra i valori di x su cui è stato allenato il trasformatore)
#come si può risolvere?

ValueError: Found unknown categories ['USA'] in column 1 during transform

In [32]:
enc = preprocessing.OneHotEncoder(handle_unknown='ignore') #inizializzo onehotencoder a cui diciamo come gestire categorie sconosciute. in questo caso gli dico di ingorarle
#il trasformatore quanto incontra categorie sconosciute durante la trasformzione dovrà ignorarle. non si preoccupa di trasformare quel dato

X = [['male', 'Spain', 'tennis'],
     ['female', 'Italy', 'football'],
     ['female', 'Italy', 'painting'],
     ['male', 'Spain', 'tennis'],
     ['female', 'France', 'football'],
     ['male', 'Italy', 'painting']]
enc.fit(X)

OneHotEncoder(handle_unknown='ignore')

In [33]:
enc.transform([['female', 'USA', 'football']]).toarray() #il codice funziona. non c'è nessun valore = 1 che corrisponde a usa. categoria sconosciuta che è stato detto di ignorarla

array([[1., 0., 0., 0., 0., 1., 0., 0.]])

In [34]:
enc.get_feature_names_out()

array(['x0_female', 'x0_male', 'x1_France', 'x1_Italy', 'x1_Spain',
       'x2_football', 'x2_painting', 'x2_tennis'], dtype=object)

In [35]:
enc.categories_

[array(['female', 'male'], dtype=object),
 array(['France', 'Italy', 'Spain'], dtype=object),
 array(['football', 'painting', 'tennis'], dtype=object)]

In [36]:
enc = preprocessing.OneHotEncoder(handle_unknown='infrequent_if_exist', min_frequency=2) #abbiamo altri valori per l'handle_unkoen
#se trovi categoria socnosciuta trasformala come se fosse la categoria meno frequente.  quindi per es in america veine messo 1 nella catoegira più frequente tra quelle su cui è stato allenato
#c'è anche uguale per il frequent anzi che l'unfrequent
X = [['male', 'Spain', 'tennis'],
     ['female', 'Italy', 'football'],
     ['female', 'Italy', 'painting'],
     ['male', 'Spain', 'tennis'],
     ['female', 'France', 'football'],
     ['male', 'Italy', 'painting']]
enc.fit(X)

OneHotEncoder(handle_unknown='infrequent_if_exist', min_frequency=2)

In [37]:
enc.categories_

[array(['female', 'male'], dtype=object),
 array(['France', 'Italy', 'Spain'], dtype=object),
 array(['football', 'painting', 'tennis'], dtype=object)]

In [38]:
enc.get_feature_names_out()

array(['x0_female', 'x0_male', 'x1_Italy', 'x1_Spain',
       'x1_infrequent_sklearn', 'x2_football', 'x2_painting', 'x2_tennis'],
      dtype=object)

In [39]:
enc.transform([['female', 'USA', 'football']]).toarray()

array([[1., 0., 0., 0., 1., 1., 0., 0.]])

In [40]:
enc.inverse_transform([[1., 0., 0., 0., 1., 1., 0., 0.]])

array([['female', 'infrequent_sklearn', 'football']], dtype=object)

### OrdinalEncoder

altro trasformatore. prima abbiamo trasformato i valori categorici con il onehotencoding. l'ordinalencoder trasforma le feature categoriche con valori che vanno da 0 a n-1. dove n è il numero di possibili valori

In [41]:
enc = preprocessing.OrdinalEncoder()

In [42]:
X = [['male', 'Spain', 'tennis'],
     ['female', 'Italy', 'football'],
     ['female', 'Italy', 'painting'],
     ['male', 'Spain', 'tennis'],
     ['female', 'France', 'football'],
     ['male', 'Italy', 'painting']]
     #in questo caso prima feature è male e female (mfemaale trasformato con 0 e male con 1 ) terza colonna ho spain italy e france avremo spain = 2, italy = 1 w france = 0.
     #valori ordinati in ordine alfabetico e poi trasformati co i valori da 0 a n-1

enc.fit(X)

OrdinalEncoder()

In [43]:
enc.categories_

[array(['female', 'male'], dtype=object),
 array(['France', 'Italy', 'Spain'], dtype=object),
 array(['football', 'painting', 'tennis'], dtype=object)]

In [44]:
enc.transform(X)

array([[1., 2., 2.],
       [0., 1., 0.],
       [0., 1., 1.],
       [1., 2., 2.],
       [0., 0., 0.],
       [1., 1., 1.]])

In [45]:
enc.transform([['female','Spain', 'football']])

array([[0., 2., 0.]])

## Discretization

discretizzazione: permette di fare quanto già visto con la funzione cut. con cut potevamo splittare, dividere i valori di un intervallo continuo in tanti intervalli. discretizziamo una variabile.
stessa cosa si fa con KBinsdiscretizer. si può dare in input il numero di gruppi in cui deve essere diviso un insieme di valori. i valori verranno poi trasformati secondo diverse strategie. ci sono diverse strateige.
uniform divide i valori in intervalli tutti della stessa ampiezza. ho un intervallo che va da 0 a 20 e voglio dividerli in 4 bins si creano 4 gruppi in cui il primo va da 0-5,5-10 ec... tutti gruppi della stesssa ampiezza
quantile divide questi valori in mdoo che in ogni gruppo ci sia lo stesso numero di sample. crea lui gli estremi di ogni intervallo.

Discretization (otherwise known as quantization or binning) provides a way to partition **continuous features into discrete values**. Certain datasets with continuous features may benefit from discretization, because discretization can transform the dataset of continuous attributes to one with only nominal attributes.

In [46]:
X = np.array([[ -3., 5., 15 ],
              [  0., 6., 14 ],
              [  6., 3., 11 ]])
est = preprocessing.KBinsDiscretizer(n_bins=[3, 2, 3], encode='ordinal').fit(X)
est

KBinsDiscretizer(encode='ordinal', n_bins=[3, 2, 3])

In [47]:
est.transform(X)

array([[0., 1., 2.],
       [1., 1., 1.],
       [2., 0., 0.]])

There are different strategies implemented in KBinsDiscretizer:

- ‘uniform’: The discretization is uniform in each feature, which means that the bin widths are constant in each dimension.

- ‘quantile’: The discretization is done on the quantiled values, which means that each bin has approximately the same number of samples.

- ‘kmeans’: The discretization is based on the centroids of a KMeans clustering procedure.

https://scikit-learn.org/stable/auto_examples/preprocessing/plot_discretization_strategies.html?highlight=kbinsdiscretizer

Feature binarization is the process of thresholding numerical features to get boolean values. This can be useful for downstream probabilistic estimators that make assumption that the input data is distributed according to a multi-variate Bernoulli distribution.

altro modo per fare la discretizazione è il binalizer trasformatore mette a 0 tutti i valori che sono sotto una certa soglia e a 1 tutti quelli che sono sopra la soglia (soglia di default è 0)

In [48]:
X = [[ 1., -1.,  2.],
     [ 2.,  0.,  0.],
     [ 0.,  1., -1.]]
binarizer = preprocessing.Binarizer().fit(X)  # threshold default value = 0
binarizer

Binarizer()

In [49]:
binarizer.transform(X)
#per ogni feature applichiamo la soglia, dove ho valore maggiore di 0 metto a 1, quelli minore o uguali a 0 li mette a 0

array([[1., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [50]:
binarizer = preprocessing.Binarizer(threshold=1.1)

In [51]:
binarizer.transform(X)

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 0.]])

## Custom transformers

Often, you will want to convert an existing Python function into a transformer to assist in data cleaning or processing.

abbiamo visto come utilizzare trasformatori già implementati. esiste function transformer. mi permette di decideere qual'è la funzione di trasformazione e usare le facility di questo trasformer, ovvero suare fit e trasform.

In [52]:
import numpy as np
from sklearn.preprocessing import FunctionTransformer
#tipicamente i trasformatori di sklearn danno in output un array numpy. applicati su array numpy o dataframe e danno in output array numpy/dataframe

transformer = FunctionTransformer(np.log1p, validate=True) #funzione data in input è il log1p. funzione calcola il logaritmo di 1+x, funzione applicata a tutti i valori diun certo array numpy e dataframe
#oltre alla funzione la function trasformer prende in input il validate. valide = TRUE significa che il dato viene prima validato e poi trasformato. validato significa che viene trasforamto in arry numpy
#se do in input un arraynumpy al trasforamtore con validate = true, x viene validato e l'output sarà un array numpy
X = np.array([[0, 1], [2, 3]])
transformer.transform(X)


array([[0.        , 0.69314718],
       [1.09861229, 1.38629436]])

The *validate* parameter indicates that the input X array should be checked before calling func. The possibilities are:

- If False, there is no input validation.

- If True, then X will be converted to a 2-dimensional NumPy array or sparse matrix. If the conversion is not possible an exception is raised.

In [53]:
type(X)

numpy.ndarray

In [54]:
type(transformer.transform(X)) #il type di ciò che viene trasformato è ancora un arraynumpy

numpy.ndarray

In [55]:
df = pd.DataFrame(X) #se trasformo la x in un dataframe, e poi do in input il dataframe al trasfromatore

In [56]:
type(df)

pandas.core.frame.DataFrame

In [57]:
type(transformer.transform(df)) #ciò che viene ritornato è sempre un array, perchè ho validate = true

numpy.ndarray

In [58]:
transformer = FunctionTransformer(np.log1p, validate=False) #stesso csoa con validate = false il risultato della trasformazione è un dataframe. diff principale è che se ho un dataframe in output
#ho ancora i nomi di colonna e quindi li posso sfruttare per fare altre trasformazioni. se in output ho array nupy non ho nomi di colonna e quindi non posso usare i nomi di colonna per selezionare una colonna

In [59]:
type(transformer.transform(df))

pandas.core.frame.DataFrame

**Pay Attention!
The result of a transformer is typically a np.array!**

In [60]:
preprocessing.StandardScaler().fit_transform(df)

array([[-1., -1.],
       [ 1.,  1.]])

In [61]:
preprocessing.StandardScaler().fit_transform(X)

array([[-1., -1.],
       [ 1.,  1.]])