<a href="https://colab.research.google.com/github/simonebugo/Big_Data/blob/main/Esercizio_in_aula_student.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import numpy as np

**1. Creazione dell'array**

Definisci una funzione che crea un array NumPy di due dimensioni (30 * 24) che riporta le temperature orarie del mese di Settembre.

Inizializza i valori con numeri decimali casuali compresi tra 10 e 30 gradi Celsius (tip: usa *np.random.uniform()*).

Note: for reproducibility, set seed at the beginning of the function definition using *np.random.seed(100)*



In [9]:
def Temp():
  np.random.seed(100)
  return np.random.uniform(10,30,[30,24])


In [10]:
arr = Temp()

In [11]:
arr

array([[20.86809884, 15.5673877 , 18.49035181, 26.89552265, 10.09437712,
        12.43138242, 23.41498169, 26.5170551 , 12.73413179, 21.50186659,
        27.82643909, 14.18404244, 13.70656439, 12.16753781, 14.39394985,
        29.57247569, 26.23366298, 13.43882025, 26.32449497, 15.48147494,
        18.63408367, 28.80059639, 26.35298758, 16.722239  ],
       [13.50820907, 17.45664093, 10.11377015, 15.04852707, 25.91325017,
        10.30509942, 21.97686754, 22.07609078, 12.10295371, 17.6388689 ,
        10.72952113, 27.80823127, 29.61841714, 11.19883978, 27.81091889,
        21.53802999, 24.84959378, 22.60367873, 21.63684385, 10.40878264,
        14.20053155, 20.89369756, 25.38230342, 15.01390458],
       [15.71791381, 27.04790176, 29.50012987, 27.69706587, 17.19015688,
        21.97717892, 17.09591223, 16.80380431, 13.56161979, 14.75388417,
        10.89724565, 20.10862859, 17.52504909, 21.85610802, 22.59883751,
        12.85200629, 28.67682599, 28.92759762, 22.04593315, 17.75532561,
  

**2. Temperatura più alta e più bassa**

Trova i valori di temperatura più alta e più bassa

In [12]:
arr.max()

np.float64(29.989583022645874)

In [14]:
arr.min()

np.float64(10.009735189505198)

**3. Temperatura media giornaliera**

Per ogni giorno (quindi per ogni riga), calcola la temperatura media e crea un nuovo array di 30 elementi che rappresenta la temperatura media giornaliera.

Trova i giorni con la temperatura media più alta e la temperatura media più bassa.

In [19]:
meanT = arr.mean(axis = 1)

In [21]:
meanT.shape

(30,)

In [24]:
min_v = meanT.min()
max_v = meanT.max()

In [29]:
np.where(meanT == min_v)[0][0]

np.int64(12)

In [30]:
np.where(meanT == max_v)[0][0]

np.int64(25)

**4. Aumento di temperatura**

Sono stati rilevati alcuni problemi nella calibrazione del misuratore, è necessario aumentare di 2 gradi ogni temperatura rispetto a quanto misurato.

In [31]:
arr = arr + 2

In [32]:
arr

array([[22.86809884, 17.5673877 , 20.49035181, 28.89552265, 12.09437712,
        14.43138242, 25.41498169, 28.5170551 , 14.73413179, 23.50186659,
        29.82643909, 16.18404244, 15.70656439, 14.16753781, 16.39394985,
        31.57247569, 28.23366298, 15.43882025, 28.32449497, 17.48147494,
        20.63408367, 30.80059639, 28.35298758, 18.722239  ],
       [15.50820907, 19.45664093, 12.11377015, 17.04852707, 27.91325017,
        12.30509942, 23.97686754, 24.07609078, 14.10295371, 19.6388689 ,
        12.72952113, 29.80823127, 31.61841714, 13.19883978, 29.81091889,
        23.53802999, 26.84959378, 24.60367873, 23.63684385, 12.40878264,
        16.20053155, 22.89369756, 27.38230342, 17.01390458],
       [17.71791381, 29.04790176, 31.50012987, 29.69706587, 19.19015688,
        23.97717892, 19.09591223, 18.80380431, 15.56161979, 16.75388417,
        12.89724565, 22.10862859, 19.52504909, 23.85610802, 24.59883751,
        14.85200629, 30.67682599, 30.92759762, 24.04593315, 19.75532561,
  

**5. Modifica di alcuni valori**

Modifica i valori dell'array in modo che il valore massimo possibile sia 30.

In [57]:
#arr[arr>30]= 30
np.where(arr>30,30,arr)

array([[22.86809884, 17.5673877 , 20.49035181, 28.89552265, 12.09437712,
        14.43138242, 25.41498169, 28.5170551 , 14.73413179, 23.50186659,
        29.82643909, 16.18404244, 15.70656439, 14.16753781, 16.39394985,
        30.        , 28.23366298, 15.43882025, 28.32449497, 17.48147494,
        20.63408367, 30.        , 28.35298758, 18.722239  ],
       [15.50820907, 19.45664093, 12.11377015, 17.04852707, 27.91325017,
        12.30509942, 23.97686754, 24.07609078, 14.10295371, 19.6388689 ,
        12.72952113, 29.80823127, 30.        , 13.19883978, 29.81091889,
        23.53802999, 26.84959378, 24.60367873, 23.63684385, 12.40878264,
        16.20053155, 22.89369756, 27.38230342, 17.01390458],
       [17.71791381, 29.04790176, 30.        , 29.69706587, 19.19015688,
        23.97717892, 19.09591223, 18.80380431, 15.56161979, 16.75388417,
        12.89724565, 22.10862859, 19.52504909, 23.85610802, 24.59883751,
        14.85200629, 30.        , 30.        , 24.04593315, 19.75532561,
  

**6. Quante volte sono stati registrati più di 23 gradi?**

In [58]:
(arr > 23).sum() #arr>23 ritorna un array booleano con true se il valore è > 30. True è interpretato come 1, facendo sum ottengo il num
#arr[arr>23].size come l'avevo fatto io

np.int64(319)

**7. Confronto di valori medi**

Calcola la differenza tra la temperatura media dei primi 3 giorni di Settembre e quella degli ultimi 3 giorni.

In [42]:
before = arr[:3] #seleziono i primi 3 giorni (0,1,2)
b_mean = before.mean()
after = arr[-3:] #selezioni gli ultimi 3
a_mean = after.mean()

In [43]:
b_mean - a_mean

np.float64(-2.1026793142211986)

**8. Creazione di una nuova colonna**

Crea una nuova colonna con il valore della mediana giornaliera

In [46]:
mediana = np.median(arr,axis = 1) #siccome è giornaliera lo devo fare lungo le righe

In [44]:
arr.shape

(30, 24)

In [49]:
mediana.shape #come si vede arr e shape hanno dimensione diversa, faccio quindi il reshape, faccio in modo che sia di 30 riga e 1 colonna

(30,)

In [54]:
mediana = mediana.reshape(30,1)

In [56]:
np.concatenate([arr,mediana],axis = 1)
# altro modo che fa stessa cosa:
#np.hstack([arr,mediana])

array([[22.86809884, 17.5673877 , 20.49035181, 28.89552265, 12.09437712,
        14.43138242, 25.41498169, 28.5170551 , 14.73413179, 23.50186659,
        29.82643909, 16.18404244, 15.70656439, 14.16753781, 16.39394985,
        30.        , 28.23366298, 15.43882025, 28.32449497, 17.48147494,
        20.63408367, 30.        , 28.35298758, 18.722239  , 20.56221774],
       [15.50820907, 19.45664093, 12.11377015, 17.04852707, 27.91325017,
        12.30509942, 23.97686754, 24.07609078, 14.10295371, 19.6388689 ,
        12.72952113, 29.80823127, 30.        , 13.19883978, 29.81091889,
        23.53802999, 26.84959378, 24.60367873, 23.63684385, 12.40878264,
        16.20053155, 22.89369756, 27.38230342, 17.01390458, 21.26628323],
       [17.71791381, 29.04790176, 30.        , 29.69706587, 19.19015688,
        23.97717892, 19.09591223, 18.80380431, 15.56161979, 16.75388417,
        12.89724565, 22.10862859, 19.52504909, 23.85610802, 24.59883751,
        14.85200629, 30.        , 30.        , 24